### PR TITLE
test bcc recipients

### PR DESCRIPTION
**Pull request by mamico**
Add `messages_from` and `messages_to` to record senders and recipients.

This is useful for checking the `bcc` that is not otherwise present in the message.

In this PR, I also added github actions to run the tests.

### CODE REVIEW

**Review by mauritsvanrees — APPROVED** [review]
Nice!

I have opened a [PR on coredev](https://github.com/plone/buildout.coredev/pull/919) to see if this has an effect there, but I guess nothing will break.  If those tests pass, this PR can be merged.

I would suggest to remove all mentions of Python 2 and Plone 5.1 and earlier from GitHub Actions and `tox.ini`.
And probably officially drop support for those versions and then we make a major release.

**Comment by mauritsvanrees** [comment]
Coverage is reported as 0.0, so something is wrong there.  But that is no blocker for me.

**Comment by mamico** [comment]
> Coverage is reported as 0.0, so something is wrong there. But that is no blocker for me.

coverage is fine when I run the tests locally

image

I suppose that there is something wrong related to coveralls.
Okay with me to carry on with the work done and address this remaining issue at a later time.

**Comment by mauritsvanrees** [comment]
I have released 3.0.0 and will include it in the Plone releases of this week.  Thanks!

**Pull request merged**
